### ISSUE TITLE
 the language?

### ISSUE THREAD

**Issue by Blackwolf8202** [715209/nginx-obs-automatic-low-bitrate-switching#86]
Have an idea if I want to change the language to the stream instead of Danish or English to Swedish where can I go in and do it?

**Comment by 715209** [comment]
Hi Blackwolf8202,

Since there is no Swedish language file you would have to create one yourself.
If you would like to do this, copy the `en.yml` from the locales folder:

https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/blob/7e5c41eadbb0b1938cea7653636a06292b33413f/locales/en.yml#L1-L5

Then rename it to something like `swe.yml` or `sv.yml` and translate the text (do not remove the %{...}).
After translating you would have to compile the program yourself or create a pull request and I will release a new version with the new language file.

**Comment by Blackwolf8202** [comment]
okay thanks =)
